<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use App\Helpers\Hasher\MD5Hash;

class MD5HashServiceProvider extends ServiceProvider
{
    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        //
        $this->app->singleton('hash', function () {
            return new MD5Hash;
        });
    }

    public function provides()
    {
//        return parent::provides(); // TODO: Change the autogenerated stub
//        return ['hash'];
    }
}
